package com.happyballoon.crm.settings.mapper;

import com.happyballoon.crm.settings.domain.DicValue;

import java.util.List;
import java.util.Map;

public interface DicValueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Fri Aug 11 22:16:06 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Fri Aug 11 22:16:06 CST 2023
     */
    int insertDicValue(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Fri Aug 11 22:16:06 CST 2023
     */
    int insertSelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Fri Aug 11 22:16:06 CST 2023
     */
    DicValue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Fri Aug 11 22:16:06 CST 2023
     */
    int updateByPrimaryKeySelective(DicValue row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_value
     *
     * @mbg.generated Fri Aug 11 22:16:06 CST 2023
     */
    int updateByPrimaryKey(DicValue row);

    /**
     * 根据typeCode删除字典值
     * @param typeCodes
     * @return
     */
    int deleteDicValueByTypeCodes(String[] typeCodes);

    /**
     * 根据typeCode查询需要删除的字典值条数
     * @param codes
     * @return
     */
    int selectDelCountByTypeCodes(String[] codes);

    /**
     * 查询所有字典值
     * @return
     */
    List<DicValue> selectAllDicValue();

    /**
     * 根据分页显示的参数，查询字典值
     * @param map
     * @return
     */
    List<DicValue> selectAllDicValueForPage(Map map);

    /**
     * 查询所有字典值的记录条数
     * @return
     */
    int selectTotalCountForPage();

    /**
     * 根据typeCode查询字典值
     * @param typeCode
     * @return
     */
    List<DicValue> selectDicValueByTypeCode(String typeCode);
}